{{- range $name, $svc := .Values.services }}
{{- if and $svc.pdb (not $svc.noPdb) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-pdb
  labels:
    app: {{ $name }}
    {{- include "online-boutique.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $svc.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ $name }}
{{- end }}
{{- end }}
