apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.prometheus.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccounts.prometheus.roleArn }}
  labels:
    {{- include "online-boutique-monitoring.labels" . | nindent 4 }}